// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env["DATABASE_URL"] ||
      "postgresql://neondb_owner:npg_V3mfAJg0GvhE@ep-nameless-union-atzfoieb.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require",
  },
});
